import Footer from "./components/fixTemplateComponent/footer";
import HeaderComponent from "./components/fixTemplateComponent/headerComponent";
import LeftColumn from "./components/fixTemplateComponent/leftComponent";
import Navbar from "./components/fixTemplateComponent/navbar";
import RightConf from "./components/fixTemplateComponent/rightConferenceDate";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gradient-to-b from-white to-blue-100  text-black">
        {/* Header */}
        <header className="w-full text-center text-xl font-semibold shadow-md flex items-center flex-col justify-center  bg-[#0284A8]">
          <HeaderComponent />
          <Navbar />
        </header>

        {/* Main Content */}
        <main className="flex flex-row w-full flex-grow">
          {/* Left Menu */}
          <aside className="w-1/4  flex flex-col items-center justify-center shadow-lg">
            <LeftColumn />
          </aside>

          {/* Middle Content */}
          <section className="flex-grow flex p-6">{children}</section>

          {/* Right Menu */}
          <aside className="w-1/4  flex flex-col  p-4 shadow-lg">
            <RightConf />
          </aside>
        </main>

        {/* Footer */}
        <footer className="w-full text-center py-4 text-sm shadow-md">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
